reviviendo/revfront/revevents/urls.py
# -*- coding: utf-8 -*-

import revfront.revevents.views

from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^list/$', revfront.revevents.views.ActivityListView.as_view(), name='list'),
    url(r'^signup/(?P<activity_pk>[0-9]+)/$', revfront.revevents.views.sign_up_view, name='signup')
)

reviviendo/revfront/revusers/urls.py
# -*- coding: utf-8 -*-

import revfront.revusers.views

from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^registration/$', revfront.revusers.views.RegistrationView.as_view(), name='registration'),
    url(r'^login/$', revfront.revusers.views.LoginView.as_view(), name='login'),
    url(r'^logout/$', revfront.revusers.views.logout_view, name='logout')
)

reviviendo/revfront/urls.py
# -*- coding: utf-8 -*-

import revfront.views

from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(r'^$', revfront.views.IndexView.as_view(), name='index'),
    url(r'^registration/$', revfront.views.PaymentView.as_view(), name='payment'),
    url(r'^faqs/$', revfront.views.FaqsView.as_view(), name='faqs'),
    url(r'^events/', include('revfront.revevents.urls', namespace="revevents")),
    url(r'^users/', include('revfront.revusers.urls', namespace="revusers"))
)

reviviendo/reviviendo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('revfront.urls', namespace="revfront"))
)

reviviendo/revfront/models.py
from django.db import models

# Create your models here.

reviviendo/revfront/revevents/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from revfront.revusers.models import Participant


class Activity(models.Model):
    """Activities that are organized in the event and may have associated Participants."""

    class Meta:
        """Meta attributes."""

        verbose_name = _(u"Actividad")
        verbose_name_plural = _(u"Actividades")

    name = models.CharField(max_length=64, unique=True, verbose_name=_(u"Nombre"))
    description = models.TextField(verbose_name=_(u"Descripción"))
    dtime = models.DateTimeField(verbose_name=_(u"Fecha y hora"))
    max_participants = models.IntegerField(verbose_name=_(u"Número de jugadores"))
    comments = models.TextField(null=True, blank=True, verbose_name=_(u"Otros comentarios"))
    participants = models.ManyToManyField(Participant, blank=True)
    image_url = models.CharField(max_length=256, verbose_name=_(u"Imagen (URL)"))

    def __unicode__(self):
        """Object's unicode representation."""

        return u'{0}'.format(self.name)

    def free_places(self):
        """Returns the number of free places for this activity."""

        return self.max_participants - len(self.participants.all())

    def has_participant(self, participant):
        """Returns true if the Participant is already in the Activity."""

        return True if participant in self.participants.all() else False

reviviendo/revfront/revusers/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


class Participant(models.Model):
    """Person that attends the event."""

    class Meta:
        """Meta attributes."""

        verbose_name = _("Participante".decode("utf8"))
        verbose_name_plural = _("Participantes".decode("utf8"))

    user = models.OneToOneField(User, verbose_name=_("Usuario asociado"))
    dni = models.CharField(max_length=16, unique=True, verbose_name=_("DNI"))
    city = models.CharField(max_length=64, verbose_name=_("Ciudad"))
    phone = models.CharField(max_length=16, verbose_name=_(u"Teléfono"))
    birthdate = models.DateField(verbose_name=_("Fecha de nacimiento"))
    comments = models.TextField(blank=True, null=True, verbose_name=_("Comentarios"))
    payment = models.BooleanField(default=False, verbose_name=_("Pago"))
    organizer = models.BooleanField(default=False, verbose_name=_("Desea organizar"))

    def __unicode__(self):
        """Object's unicode representation."""

        return u'{0}, {1} ({2})'.format(self.user.last_name, self.user.first_name, self.user.email)

reviviendo/revfront/revusers/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from revfront.revusers.models import Participant
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError


class ParticipantLoginForm(forms.Form):
    """Form to handle participant login."""

    username = forms.CharField(max_length=128, required=True, label=_("Nombre de usuario"))
    password = forms.CharField(max_length=128, required=True, label=_("Password"), widget=forms.PasswordInput)

    def login(self, request):
        """Attempts to login the user."""

        user = authenticate(username=self.cleaned_data["username"], password=self.cleaned_data["password"])

        if user is not None:
            if user.is_active:
                try:
                    Participant.objects.get(user=user)
                    login(request, user)
                    return True
                except Participant.DoesNotExist:
                    pass

        return False


class ParticipantForm(UserCreationForm):
    """Custom UserCreationForm that creates an associated Participant."""

    first_name = forms.CharField(max_length=30, required=True, label=_("Nombre"))
    last_name = forms.CharField(max_length=30, required=True, label=_("Apellidos"))
    email = forms.EmailField(required=True, label=_("Email"))
    dni = forms.CharField(max_length=16, required=True, label=_("DNI"))
    city = forms.CharField(max_length=64, required=True, label=_("Ciudad"))
    phone = forms.CharField(max_length=16, required=True, label=_(u"Teléfono"))
    birthdate = forms.DateField(
        required=True, label=_("Fecha de nacimiento"),
        widget=forms.DateInput(attrs={"placeholder": _("dd/mm/aaaa")}))
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={
        "placeholder": _("Alergias, restricciones alimentarias u otros comentarios que consideres oportunos.")
    }), label=_("Comentarios"))
    organizer = forms.BooleanField(required=False, label=_(u"¿Quieres organizar un ReV?"))

    class Meta:
        """Meta attributes."""

        model = User
        fields = (
            "username", "first_name", "last_name", "email", "password1",
            "password2", "dni", "city", "phone", "birthdate", "comments", "organizer")

    def clean_dni(self):
        """Check that this DNI is unique."""

        try:
            Participant.objects.get(dni=self.cleaned_data["dni"])
            raise ValidationError(
                _('Ya existe un participante con DNI: %(dni)s'),
                code='uniquedni',
                params={'dni': self.cleaned_data["dni"]})
        except Participant.DoesNotExist:
            pass

        return self.cleaned_data["dni"]

    def save(self, commit=True):
        """Override parent save() method to add Participant relationship."""

        user = super(ParticipantForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()

        participant = Participant(
            dni=self.cleaned_data["dni"], city=self.cleaned_data["city"], phone=self.cleaned_data["phone"],
            birthdate=self.cleaned_data["birthdate"], comments=self.cleaned_data["comments"], user=user,
            organizer=self.cleaned_data["organizer"])

        if commit:
            participant.save()

        return user

reviviendo/revfront/revevents/views.py
# -*- coding: utf-8 -*-

from django.views.generic.list import ListView
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from revfront.revevents.models import Activity
from django.contrib.auth.decorators import login_required
from revfront.revusers.models import Participant


class ActivityListView(ListView):
    """List view for the Activity model."""

    model = Activity

    def dispatch(self, request, *args, **kwargs):
        """Override dispatch to logout admins that enter the activity page."""

        if self.request.user.is_authenticated():
            try:
                self.request.user.participant
            except Participant.DoesNotExist:
                return redirect("revfront:revusers:logout")

        return super(ActivityListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """Overrides context to add menu and participant info."""

        activities = self.get_queryset()

        context = super(ActivityListView, self).get_context_data(**kwargs)
        context['menu'] = 'revevents:list'
        context['subscriptions'] = dict()

        if self.request.user.is_authenticated():
            participant = self.request.user.participant
            context['subscriptions'] = dict((act.pk, act.has_participant(participant)) for act in activities)

        return context

    def get_queryset(self):
        """Override queryset to order by datetime."""

        return Activity.objects.all().order_by("dtime")


@login_required
def sign_up_view(request, activity_pk):
    """View to handle Participants signing up for Activities."""

    activity = get_object_or_404(Activity, pk=activity_pk)

    if not request.user.participant.payment:
        raise Http404("Cannot sign up without accepted payment")

    if activity.has_participant(request.user.participant):
        raise Http404("Participant is already in the Activity")

    if not activity.free_places():
        raise Http404("Attempt to sign up for full Activity")

    activity.participants.add(request.user.participant)
    activity.save()

    return redirect("revfront:revevents:list")

reviviendo/revfront/revusers/views.py
# -*- coding: utf-8 -*-

from django.views.generic.edit import FormView
from revfront.revusers.forms import ParticipantForm, ParticipantLoginForm
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


class RegistrationView(FormView):
    """Participant registration view."""

    template_name = "revusers/registration.html"
    form_class = ParticipantForm
    success_url = reverse_lazy("revfront:revusers:registration")

    def get_context_data(self, **kwargs):
        """Overrides context to add menu."""

        context = super(RegistrationView, self).get_context_data(**kwargs)
        context['menu'] = 'payment'

        return context

    def form_valid(self, form):
        """Save User and Participant objects."""

        form.save()
        messages.success(self.request, _(u"¡Te has registrado correctamente!"))

        return super(RegistrationView, self).form_valid(form)


class LoginView(FormView):
    """Participant login view."""

    template_name = "revusers/login.html"
    form_class = ParticipantLoginForm
    success_url = reverse_lazy("revfront:index")

    def get_context_data(self, **kwargs):
        """Overrides context to add menu."""

        context = super(LoginView, self).get_context_data(**kwargs)
        context['menu'] = 'revusers:login'

        return context

    def form_valid(self, form):
        """Save User and Participant objects."""

        logout(self.request)
        login_ok = form.login(self.request)

        if not login_ok:
            messages.warning(self.request, _(u"El usuario o el password son inválidos"))
            return redirect("revfront:revusers:login")

        return super(LoginView, self).form_valid(form)


@login_required
def logout_view(request):
    """Logout view."""

    logout(request)
    return redirect("revfront:revusers:login")

reviviendo/revfront/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    """Homepage index view."""

    template_name = "revfront/index.html"

    def get_context_data(self, **kwargs):
        """Overrides context to add menu."""

        context = super(IndexView, self).get_context_data(**kwargs)
        context['menu'] = 'index'

        return context


class PaymentView(TemplateView):
    """Payment info view."""

    template_name = "revfront/payment.html"

    def get_context_data(self, **kwargs):
        """Overrides context to add menu."""

        context = super(PaymentView, self).get_context_data(**kwargs)
        context['menu'] = 'payment'

        return context


class FaqsView(TemplateView):
    """Frequently asked questions view."""

    template_name = "revfront/faqs.html"

    def get_context_data(self, **kwargs):
        """Overrides context to add menu."""

        context = super(FaqsView, self).get_context_data(**kwargs)
        context['menu'] = 'faqs'

        return context

reviviendo/revfront/templates/revfront/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Reviviendo">
    <meta name="author" content="agmangas@gmail.com">

    <title>{% block title %}Jornadas Reviviendo{% endblock %}</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/darkly/bootstrap.min.css">
    <link rel="stylesheet" href={% static "revfront/css/custom.css" %}>
    {% block styles %}{% endblock %}
</head>
<body>
{% include 'revfront/navbar.html' %}

<div class="container" id="main-container">
    {% block body %}{% endblock %}
    <footer>
        <a href="http://www.zdezombies.com" target="_blank">
            <img class="pull-left" src={% static "revfront/img/zdezombies-logo.png" %}>
        </a>
        <span class="lead pull-right text-muted">© Jornadas Reviviendo 2014</span>
    </footer>
</div>

<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
<script src={% static "revfront/js/sprintf.min.js" %}></script>
<script src={% static "revfront/js/bootbox.min.js" %}></script>
{% block javascripts %}{% endblock %}
</body>
</html>

reviviendo/revfront/templates/revfront/faqs.html
{% extends 'revfront/base.html' %}

{% load staticfiles %}

{% block body %}

    <div class="page-header">
        <h1>FAQs
            <small>Preguntas frecuentes</small>
        </h1>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p class="lead text-muted">¿Qué es ReViviendo?</p>

            <div class="well text-justify">
                ReViviendo son las jornadas colaborativas de Roles en Vivo que organiza Z de Zombies.
            </div>

            <p class="lead text-muted add-margin-top">¿Qué es un juego de Rol en Vivo (ReV)?</p>

            <div class="well text-justify">
                Un juego de Rol en Vivo, ReV por sus iniciales, es una actividad similar a una obra teatral, destinada a
                trabajar la interpretación, la inteligencia y el trabajo en grupo de los participantes. Para aquellos
                familiarizados con los juegos de rol narrativo, de cartas, o de videoconsola/ordenador, se trata
                esencialmente de lo mismo llevado a un terreno real. Al sacar a los jugadores fuera de la mesa/pantalla,
                se
                consigue una implicación mucho más activa y social por su parte, permitiendo el desarrollo de múltiples
                tramas y personajes en paralelo sin ralentizar el juego.
            </div>

            <p class="lead text-muted add-margin-top">¿Cómo funcionan las jornadas ReViviendo?</p>

            <div class="well text-justify">
                A diferencia del Rol en Vivo de Z de Zombies, las ReViviendo están compuestas por un conjunto de ReV que
                se
                distribuyen entre los dos días que duran las jornadas, cubriendo todas las franjas horarias. La temática
                de
                las actividades es libre y podrá estar basada en cualquier cosa que te puedas imaginar: libros,
                películas,
                cómics, videojuegos, hechos históricos, etc., pretendiendo así abarcar una gran variedad de gustos y
                acercarnos a todos los participantes.
            </div>

            <p class="lead text-muted add-margin-top">¿Por qué colaborativas?</p>

            <div class="well text-justify">
                Aunque es Z de Zombies quien organiza el evento, se encarga de la logística, gestión del lugar, etc., no
                necesariamente se encargará de dirigir todos los ReV. Nuestra geografía está llena de excelentes
                asociaciones y personas con experiencia y ganas de llevar sus ideas a otros lugares, y Asturias estará
                encantada de recibiros. Tanto si eres Asociación como persona, y tengas mucha o poca experiencia,
                anímate,
                cuéntanos tu idea, tráenos tu partida y te haremos un hueco en las jornadas. (A la hora de inscribirte a
                las
                jornadas, indícanos que quieres organizar un ReV y te enviaremos un formulario para que nos expliques
                con
                detalle en que consiste).
            </div>

            <p class="lead text-muted add-margin-top">¿Dónde, cuándo y cuánto?</p>

            <div class="well text-justify">
                Esta segunda edición tendrá lugar, nuevamente, en el
                <a href="https://goo.gl/maps/87vlG" target="_blank">
                    Palacio de la Bouza, en Riberas (Soto del Barco, Asturias)
                </a>
                los días 25 y 26 de Octubre, y su precio será de 45€ por persona (Incluye comida, cena y
                alojamiento del sábado y desayuno y comida del domingo).
            </div>

            <p class="lead text-muted add-margin-top">¿Cómo me apunto?</p>

            <div class="well text-justify">
                El proceso está explicado en la sección de <a href={% url 'revfront:payment' %}>Inscripción</a>.
            </div>

            <p class="lead text-muted add-margin-top">¿Cómo me apunto a los roles en vivo una vez inscrito?</p>

            <div class="well text-justify">
                En cuanto confirmemos tu pago (suele tardar entre uno y dos días), te enviaremos un email.
                A partir de este momento podrás apuntarte a las actividades a través de nuestra web.
            </div>

            <p class="lead text-muted add-margin-top">¿Quién las organiza?</p>

            <div class="well text-justify">
                Como hemos dicho anteriormente, es Z de Zombies quien organiza las jornadas, pero además contará con la
                ayuda de otras asociaciones y personas para ampliar la oferta de ReVs. Cualquiera puede participar en
                las jornadas ReViviendo. ¡Animaros a enviarnos vuestros ReVs!
            </div>

            <p class="lead text-muted add-margin-top">¿Más dudas?</p>

            <div class="well text-justify">
                Para cualquier tipo de duda, información o sugerencia, puedes enviarnos un mail a
                reviviendo@zdezombies.com
            </div>

        </div>
    </div>

{% endblock %}

reviviendo/revfront/templates/revfront/index.html
{% extends 'revfront/base.html' %}

{% load staticfiles %}

{% block body %}

<div class="page-header">
    <h1>¡Bienvenid@!
        <small>La Asociación Z de Zombies presenta:</small>
    </h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <img class="img-thumbnail" src={% static "revfront/img/reviviendo-home.jpg" %}>
        </div>
    </div>
</div>

{% endblock %}

reviviendo/revfront/templates/revfront/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span id="collapse-icon" class="glyphicon glyphicon-align-justify"></span>
            </button>
            <a class="navbar-brand" href={% url 'revfront:index' %}>
                Jornadas Reviviendo
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li {% if menu == "payment" %} class="active" {% endif %}>
                    <a href={% url 'revfront:payment' %}>Inscripción</a>
                </li>
                <li {% if menu == "faqs" %} class="active" {% endif %}>
                    <a href={% url 'revfront:faqs' %}>FAQs</a>
                </li>
                <li {% if menu == "revevents:list" %} class="active" {% endif %}>
                    <a href={% url 'revfront:revevents:list' %}>Actividades</a>
                </li>
                {% if not user.is_authenticated %}
                    <li {% if menu == "revusers:login" %} class="active" {% endif %}>
                        <a href={% url 'revfront:revusers:login' %}>Acceder</a>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <p class="navbar-text navbar-right">
                    <span class="text-info">
                        <i class="fa fa-user"></i> &nbsp;
                        {{ user.username }} &nbsp;
                        <a class="btn btn-info btn-xs logout-btn-fix" href={% url 'revfront:revusers:logout' %}>
                            <i class="fa fa-sign-out"></i> Salir
                        </a> &nbsp;
                        {% if not user.is_staff %}
                            {% if user.participant.payment %}
                                <a class="btn btn-success btn-xs logout-btn-fix disabled">
                                    Pago OK
                                </a>
                            {% else %}
                                <a class="btn btn-danger btn-xs logout-btn-fix disabled">
                                    Pago pendiente
                                </a>
                            {% endif %}
                        {% endif %}
                    </span>
                </p>
            {% endif %}
        </div>
    </div>
</nav>

reviviendo/revfront/templates/revfront/payment.html
{% extends 'revfront/base.html' %}

{% load staticfiles %}

{% block body %}

    <div class="page-header">
        <h1>Inscripciones
            <small>Pasos necesarios para completar tu inscripción</small>
        </h1>
    </div>

    <div class="row">
        <div class="col-md-12">
            <ul class="list-group">
                <li class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <span class="text-info">0</span> &nbsp; Registro
                    </h4>

                    <p class="add-margin-top no-margin-bottom">Antes de nada debes apuntarte en la
                        <a href={% url 'revfront:revusers:registration' %}>Sección de Registro</a></p>
                </li>
                <li class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <span class="text-info">1</span> &nbsp; Pago
                    </h4>
                    <table class="table table-bordered table-condensed add-margin-top no-margin-bottom">
                        <tbody>
                        <tr>
                            <td class="">Método</td>
                            <td class="active">Ingreso o transferencia bancaria</td>
                        </tr>
                        <tr>
                            <td class="">Importe</td>
                            <td class="active">45 euros</td>
                        </tr>
                        <tr>
                            <td class="">Banco</td>
                            <td class="active">Banco Sabadell (Herrero)</td>
                        </tr>
                        <tr>
                            <td class="">Cuenta</td>
                            <td class="active">0081 5660 14 0001138724</td>
                        </tr>
                        <tr>
                            <td class="">Asunto</td>
                            <td class="active">
                                Debes indicar uno de los siguientes datos:
                                <span class="text-muted">DNI</span>,
                                <span class="text-muted">Email de registro</span> o
                                <span class="text-muted">Nombre y Apellidos</span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </li>
                <li class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <span class="text-info">2</span> &nbsp; Confirmación
                    </h4>

                    <p class="add-margin-top no-margin-bottom">En un plazo de pocos días confirmaremos tu pago y
                        te enviaremos un email, a partir de este momento podrás apuntarte a las actividades</p>
                </li>
            </ul>
        </div>
    </div>

{% endblock %}